# ============================================
# Boussole - Forecast Model
# ============================================

"""
Forecast model for storing time-series forecasts generated by Prophet.
"""

from sqlalchemy import Column, Integer, String, Float, DateTime, Boolean, ForeignKey, Text
from sqlalchemy.orm import relationship
from datetime import datetime
from app.db.base import Base


class Forecast(Base):
    """
    Forecast model for storing Prophet-generated forecasts.
    """
    
    __tablename__ = "forecasts"
    
    id = Column(Integer, primary_key=True, index=True)
    metric_id = Column(Integer, ForeignKey("metrics.id", ondelete="CASCADE"), nullable=False, index=True)
    wilaya_id = Column(Integer, ForeignKey("wilayas.id", ondelete="SET NULL"), index=True)
    
    # Forecast period
    forecast_period = Column(String(20), index=True, nullable=False)  # e.g., "2025-Q1", "2025-01"
    year = Column(Integer, index=True)
    quarter = Column(String(5))  # Q1, Q2, Q3, Q4
    month = Column(Integer)  # 1-12
    
    # Forecast values
    forecast_value = Column(Float, nullable=False)
    lower_bound = Column(Float)  # Prophet prediction interval lower bound
    upper_bound = Column(Float)  # Prophet prediction interval upper bound
    confidence_interval = Column(Float, default=0.95)  # Confidence level (0.80, 0.95, etc.)
    
    # Forecast metadata
    forecast_horizon = Column(Integer, default=1)  # Number of periods ahead
    model_version = Column(String(50))  # Prophet version or model identifier
    model_params = Column(Text)  # Prophet model parameters as JSON
    
    # Quality metrics
    mae = Column(Float)  # Mean Absolute Error
    mape = Column(Float)  # Mean Absolute Percentage Error
    rmse = Column(Float)  # Root Mean Squared Error
    
    # Metadata
    notes = Column(Text)
    is_published = Column(Boolean, default=False)  # Whether forecast is visible to users
    
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    
    # Relationships
    metric = relationship("Metric", back_populates="forecasts")
    wilaya = relationship("Wilaya")
    
    def __repr__(self):
        return f"<Forecast(id={self.id}, period={self.forecast_period}, value={self.forecast_value})>"
