"use client";

import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import html2canvas from "html2canvas";

interface ExportOptions {
    query: string;
    layoutWidgets: any[];
    chartContainerRef: React.RefObject<HTMLDivElement | null>;
}

export async function generateExplorerPDF({ query, layoutWidgets, chartContainerRef }: ExportOptions) {
    const pdf = new jsPDF("p", "mm", "a4");
    const pageWidth = pdf.internal.pageSize.getWidth();
    const pageHeight = pdf.internal.pageSize.getHeight();
    const margin = 15;
    const contentWidth = pageWidth - margin * 2;
    let yPos = margin;

    // ── Helpers ─────────────────────────────────────────
    const addPage = () => {
        pdf.addPage();
        yPos = margin;
        drawFooter();
    };

    const checkSpace = (needed: number) => {
        if (yPos + needed > pageHeight - 25) addPage();
    };

    const drawFooter = () => {
        const pageCount = pdf.getNumberOfPages();
        pdf.setFontSize(8);
        pdf.setTextColor(160, 160, 160);
        pdf.text(
            `Boussole Intelligence Report  •  Page ${pageCount}  •  Generated ${new Date().toLocaleDateString("en-GB")}`,
            pageWidth / 2, pageHeight - 8,
            { align: "center" }
        );
    };

    // ── 1. Cover Header ─────────────────────────────────
    // Navy gradient header box
    pdf.setFillColor(15, 23, 42); // slate-900
    pdf.rect(0, 0, pageWidth, 55, "F");

    // Accent bar
    pdf.setFillColor(202, 178, 130); // wheat accent
    pdf.rect(0, 55, pageWidth, 3, "F");

    // Title
    pdf.setFont("helvetica", "bold");
    pdf.setFontSize(26);
    pdf.setTextColor(255, 255, 255);
    pdf.text("Boussole", margin, 22);

    pdf.setFont("helvetica", "normal");
    pdf.setFontSize(12);
    pdf.setTextColor(202, 178, 130);
    pdf.text("Intelligence Report", margin, 30);

    // Date
    pdf.setFontSize(9);
    pdf.setTextColor(180, 190, 210);
    pdf.text(new Date().toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" }), margin, 40);

    // Query badge
    pdf.setFontSize(9);
    pdf.setTextColor(220, 220, 240);
    const queryText = `Query: "${query}"`;
    pdf.text(queryText, margin, 48);

    yPos = 68;

    // ── 2. Executive Summary Section ────────────────────
    pdf.setFont("helvetica", "bold");
    pdf.setFontSize(16);
    pdf.setTextColor(15, 23, 42);
    pdf.text("Executive Summary", margin, yPos);
    yPos += 3;

    // Underline
    pdf.setDrawColor(202, 178, 130);
    pdf.setLineWidth(0.8);
    pdf.line(margin, yPos, margin + 50, yPos);
    yPos += 8;

    // Summary text
    pdf.setFont("helvetica", "normal");
    pdf.setFontSize(10);
    pdf.setTextColor(60, 60, 60);

    const summaryText = `This report was generated by Boussole's AI-powered Data Explorer in response to the query "${query}". ` +
        `The analysis covers ${layoutWidgets.length} visualization modules spanning key performance indicators, trend analyses, ` +
        `and comparative studies drawn from Algeria's comprehensive economic metrics database. ` +
        `All data points are sourced from verified national registries and real-time collection pipelines.`;

    const summaryLines = pdf.splitTextToSize(summaryText, contentWidth);
    pdf.text(summaryLines, margin, yPos);
    yPos += summaryLines.length * 5 + 8;

    // ── 3. KPI Summary Table ────────────────────────────
    const kpiWidgets = layoutWidgets.filter(w => w.component === "kpi_card");
    const metricGridWidgets = layoutWidgets.filter(w => w.component === "metric_grid");

    if (kpiWidgets.length > 0 || metricGridWidgets.length > 0) {
        checkSpace(40);
        pdf.setFont("helvetica", "bold");
        pdf.setFontSize(14);
        pdf.setTextColor(15, 23, 42);
        pdf.text("Key Performance Indicators", margin, yPos);
        yPos += 8;

        const kpiData = kpiWidgets.map(w => [
            w.title || w.metric_slug,
            w.metric_slug,
            w.filters?.sector_slug || "All Sectors",
            w.trend_type === "up" ? "↑ Growing" : w.trend_type === "down" ? "↓ Declining" : "→ Stable"
        ]);

        if (kpiData.length > 0) {
            autoTable(pdf, {
                startY: yPos,
                head: [["Indicator", "Metric Slug", "Sector Filter", "Expected Trend"]],
                body: kpiData,
                theme: "grid",
                headStyles: { fillColor: [15, 23, 42], textColor: [255, 255, 255], fontSize: 9, fontStyle: "bold" },
                bodyStyles: { fontSize: 9, textColor: [50, 50, 50] },
                alternateRowStyles: { fillColor: [248, 250, 252] },
                margin: { left: margin, right: margin },
                columnStyles: {
                    0: { fontStyle: "bold", cellWidth: 50 },
                    3: { cellWidth: 30 }
                }
            });
            yPos = (pdf as any).lastAutoTable.finalY + 10;
        }
    }

    // ── 4. Widget Configuration Breakdown ───────────────
    const chartWidgets = layoutWidgets.filter(w =>
        !["kpi_card", "metric_grid", "insight_panel", "filter_panel"].includes(w.component)
    );

    if (chartWidgets.length > 0) {
        checkSpace(40);
        pdf.setFont("helvetica", "bold");
        pdf.setFontSize(14);
        pdf.setTextColor(15, 23, 42);
        pdf.text("Analytical Components", margin, yPos);
        yPos += 8;

        const componentNames: Record<string, string> = {
            line_chart: "📈 Trend Line Chart",
            bar_chart: "📊 Bar Chart",
            pie_chart: "🥧 Pie Chart",
            radar_chart: "🎯 Radar Chart",
            composed_chart: "📉 Composed Chart",
            scatter_plot: "⚬ Scatter Plot",
            treemap: "🗺️ Treemap",
            funnel_chart: "🔻 Funnel Chart",
            comparison_card: "⚖️ Comparison Card",
            gauge_card: "🎯 Gauge Card",
            growth_indicator: "📈 Growth Indicator",
            ranking_card: "🏆 Ranking Card",
            choropleth_map: "🗺️ Choropleth Map",
            data_table: "📋 Data Table",
            stacked_area_chart: "📊 Stacked Area",
            sentiment_timeline: "🕐 Timeline",
            executive_snapshot: "📋 Executive Snapshot",
        };

        const chartData = chartWidgets.map(w => [
            componentNames[w.component] || w.component,
            w.title || "Untitled",
            w.metric_slug || (w.metric_slugs || []).join(", ") || "—",
            w.group_by || "—",
        ]);

        autoTable(pdf, {
            startY: yPos,
            head: [["Type", "Title", "Metric(s)", "Grouped By"]],
            body: chartData,
            theme: "striped",
            headStyles: { fillColor: [202, 178, 130], textColor: [15, 23, 42], fontSize: 9, fontStyle: "bold" },
            bodyStyles: { fontSize: 9, textColor: [50, 50, 50] },
            margin: { left: margin, right: margin },
        });
        yPos = (pdf as any).lastAutoTable.finalY + 10;
    }

    // ── 5. Insight Panels ───────────────────────────────
    const insightWidgets = layoutWidgets.filter(w => w.component === "insight_panel");
    if (insightWidgets.length > 0) {
        checkSpace(30);
        pdf.setFont("helvetica", "bold");
        pdf.setFontSize(14);
        pdf.setTextColor(15, 23, 42);
        pdf.text("AI-Generated Insights", margin, yPos);
        yPos += 8;

        insightWidgets.forEach((insight, idx) => {
            checkSpace(20);

            // Insight box
            pdf.setFillColor(248, 250, 252);
            pdf.setDrawColor(202, 178, 130);
            pdf.roundedRect(margin, yPos - 2, contentWidth, 18, 2, 2, "FD");

            pdf.setFont("helvetica", "bold");
            pdf.setFontSize(9);
            pdf.setTextColor(15, 23, 42);
            pdf.text(`Insight ${idx + 1}`, margin + 4, yPos + 4);

            pdf.setFont("helvetica", "normal");
            pdf.setFontSize(9);
            pdf.setTextColor(80, 80, 80);
            const insightLines = pdf.splitTextToSize(insight.text || "AI insight not available", contentWidth - 10);
            pdf.text(insightLines, margin + 4, yPos + 10);
            yPos += 22;
        });
    }

    // ── 6. Capture Live Charts as Images ────────────────
    if (chartContainerRef?.current) {
        checkSpace(20);
        pdf.setFont("helvetica", "bold");
        pdf.setFontSize(14);
        pdf.setTextColor(15, 23, 42);
        pdf.text("Visual Analysis (Live Charts)", margin, yPos);
        yPos += 10;

        try {
            const canvas = await html2canvas(chartContainerRef.current, {
                scale: 2,
                useCORS: true,
                backgroundColor: "#ffffff",
                logging: false,
            });

            const imgData = canvas.toDataURL("image/png");
            const imgWidth = contentWidth;
            const imgHeight = (canvas.height / canvas.width) * imgWidth;

            // Split across pages if needed
            let remainingHeight = imgHeight;
            let sourceY = 0;

            while (remainingHeight > 0) {
                const availableHeight = pageHeight - yPos - 20;
                const chunkHeight = Math.min(remainingHeight, availableHeight);

                pdf.addImage(imgData, "PNG", margin, yPos, imgWidth, imgHeight, undefined, "FAST");

                remainingHeight -= chunkHeight;
                if (remainingHeight > 0) {
                    addPage();
                }
                yPos += chunkHeight + 5;
                sourceY += chunkHeight;
            }
        } catch (err) {
            console.error("Chart capture failed:", err);
            pdf.setFont("helvetica", "italic");
            pdf.setFontSize(9);
            pdf.setTextColor(150, 150, 150);
            pdf.text("(Chart capture was not available for this export)", margin, yPos);
            yPos += 8;
        }
    }

    // ── 7. Methodology Note ─────────────────────────────
    checkSpace(40);

    pdf.setFillColor(248, 250, 252);
    pdf.roundedRect(margin, yPos, contentWidth, 30, 2, 2, "F");

    pdf.setFont("helvetica", "bold");
    pdf.setFontSize(10);
    pdf.setTextColor(15, 23, 42);
    pdf.text("📋 Data Methodology", margin + 4, yPos + 6);

    pdf.setFont("helvetica", "normal");
    pdf.setFontSize(8);
    pdf.setTextColor(100, 100, 100);
    const methodLines = pdf.splitTextToSize(
        "This report is generated by Boussole's AI orchestration engine. Metrics are aggregated from verified national " +
        "economic registries across Algeria's 58 wilayas and 14 economic sectors. Time series data covers 2018–2024 with " +
        "year-over-year trend calculations. The AI selects optimal visualization types based on query intent analysis. " +
        "All figures are subject to data availability and verification status.",
        contentWidth - 8
    );
    pdf.text(methodLines, margin + 4, yPos + 12);

    // ── Footer on all pages ─────────────────────────────
    const totalPages = pdf.getNumberOfPages();
    for (let i = 1; i <= totalPages; i++) {
        pdf.setPage(i);
        drawFooter();
    }

    // ── Save ────────────────────────────────────────────
    const sanitizedQuery = query.replace(/[^a-zA-Z0-9]/g, "_").slice(0, 40);
    pdf.save(`Boussole_Report_${sanitizedQuery}_${new Date().toISOString().slice(0, 10)}.pdf`);
}
