"""remove_unique_constraint_on_metric_slug

Revision ID: 487bf0bd0399
Revises: f53c956942e9
Create Date: 2026-02-21 20:35:09.609721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '487bf0bd0399'
down_revision: Union[str, None] = 'f53c956942e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_metrics_slug', table_name='metrics')
    op.create_index(op.f('ix_metrics_slug'), 'metrics', ['slug'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_metrics_slug'), table_name='metrics')
    op.create_index('ix_metrics_slug', 'metrics', ['slug'], unique=True)
    # ### end Alembic commands ###
