"""Add insights table

Revision ID: e32fac5e58cd
Revises: c3d4e5f6a7b8
Create Date: 2026-02-19 22:10:23.302877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e32fac5e58cd'
down_revision: Union[str, None] = 'c3d4e5f6a7b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sector_id', sa.Integer(), nullable=True),
    sa.Column('indicator_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title_en', sa.String(length=300), nullable=False),
    sa.Column('title_fr', sa.String(length=300), nullable=False),
    sa.Column('title_ar', sa.String(length=300), nullable=False),
    sa.Column('content_en', sa.Text(), nullable=False),
    sa.Column('content_fr', sa.Text(), nullable=False),
    sa.Column('content_ar', sa.Text(), nullable=False),
    sa.Column('importance_score', sa.Float(), nullable=True),
    sa.Column('period', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['indicator_id'], ['indicators.id'], name=op.f('fk_insights_indicator_id_indicators'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sector_id'], ['sectors.id'], name=op.f('fk_insights_sector_id_sectors'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_insights'))
    )
    op.create_index(op.f('ix_insights_id'), 'insights', ['id'], unique=False)
    op.create_index(op.f('ix_insights_indicator_id'), 'insights', ['indicator_id'], unique=False)
    op.create_index(op.f('ix_insights_sector_id'), 'insights', ['sector_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_insights_sector_id'), table_name='insights')
    op.drop_index(op.f('ix_insights_indicator_id'), table_name='insights')
    op.drop_index(op.f('ix_insights_id'), table_name='insights')
    op.drop_table('insights')
    # ### end Alembic commands ###
