"""Add missing intent models

Revision ID: b5fa0ab11c67
Revises: 14b3d708014e
Create Date: 2026-02-20 20:08:56.839715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5fa0ab11c67'
down_revision: Union[str, None] = '14b3d708014e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_provider_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_name', sa.String(), nullable=False),
    sa.Column('api_key', sa.String(), nullable=False),
    sa.Column('api_base_url', sa.String(), nullable=True),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_provider_configs'))
    )
    op.create_index(op.f('ix_ai_provider_configs_is_active'), 'ai_provider_configs', ['is_active'], unique=False)
    op.create_index(op.f('ix_ai_provider_configs_provider_name'), 'ai_provider_configs', ['provider_name'], unique=True)
    op.create_table('intent_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('query', sa.String(length=1000), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('parsed_intent', sa.JSON(), nullable=False),
    sa.Column('is_accurate', sa.Boolean(), nullable=True),
    sa.Column('feedback_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_intent_logs'))
    )
    op.create_index(op.f('ix_intent_logs_created_at'), 'intent_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_intent_logs_id'), 'intent_logs', ['id'], unique=False)
    op.create_index(op.f('ix_intent_logs_query'), 'intent_logs', ['query'], unique=False)
    op.create_table('static_intents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(length=255), nullable=False),
    sa.Column('mapped_intent', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_static_intents'))
    )
    op.create_index(op.f('ix_static_intents_id'), 'static_intents', ['id'], unique=False)
    op.create_index(op.f('ix_static_intents_keyword'), 'static_intents', ['keyword'], unique=True)
    op.create_table('system_prompts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_system_prompts'))
    )
    op.create_index(op.f('ix_system_prompts_id'), 'system_prompts', ['id'], unique=False)
    op.create_index(op.f('ix_system_prompts_name'), 'system_prompts', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_system_prompts_name'), table_name='system_prompts')
    op.drop_index(op.f('ix_system_prompts_id'), table_name='system_prompts')
    op.drop_table('system_prompts')
    op.drop_index(op.f('ix_static_intents_keyword'), table_name='static_intents')
    op.drop_index(op.f('ix_static_intents_id'), table_name='static_intents')
    op.drop_table('static_intents')
    op.drop_index(op.f('ix_intent_logs_query'), table_name='intent_logs')
    op.drop_index(op.f('ix_intent_logs_id'), table_name='intent_logs')
    op.drop_index(op.f('ix_intent_logs_created_at'), table_name='intent_logs')
    op.drop_table('intent_logs')
    op.drop_index(op.f('ix_ai_provider_configs_provider_name'), table_name='ai_provider_configs')
    op.drop_index(op.f('ix_ai_provider_configs_is_active'), table_name='ai_provider_configs')
    op.drop_table('ai_provider_configs')
    # ### end Alembic commands ###
