"""initial_schema

Revision ID: 08d602bd490d
Revises: 
Create Date: 2026-02-18 12:04:37.266518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08d602bd490d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sectors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('name_en', sa.String(length=200), nullable=False),
    sa.Column('name_fr', sa.String(length=200), nullable=False),
    sa.Column('name_ar', sa.String(length=200), nullable=False),
    sa.Column('description_en', sa.Text(), nullable=True),
    sa.Column('description_fr', sa.Text(), nullable=True),
    sa.Column('description_ar', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sectors'))
    )
    op.create_index(op.f('ix_sectors_id'), 'sectors', ['id'], unique=False)
    op.create_index(op.f('ix_sectors_slug'), 'sectors', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('organization', sa.String(length=255), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('preferred_language', sa.String(length=10), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('wilayas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name_en', sa.String(length=100), nullable=False),
    sa.Column('name_fr', sa.String(length=100), nullable=False),
    sa.Column('name_ar', sa.String(length=100), nullable=False),
    sa.Column('name_arabic', sa.String(length=100), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('area_km2', sa.Float(), nullable=True),
    sa.Column('population', sa.Integer(), nullable=True),
    sa.Column('region', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wilayas'))
    )
    op.create_index(op.f('ix_wilayas_code'), 'wilayas', ['code'], unique=True)
    op.create_index(op.f('ix_wilayas_id'), 'wilayas', ['id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('title_en', sa.String(length=500), nullable=True),
    sa.Column('title_fr', sa.String(length=500), nullable=True),
    sa.Column('title_ar', sa.String(length=500), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=200), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('document_type', sa.String(length=50), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('file_type', sa.String(length=50), nullable=True),
    sa.Column('sector_id', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('is_indexed', sa.Boolean(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_documents_owner_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sector_id'], ['sectors.id'], name=op.f('fk_documents_sector_id_sectors'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents'))
    )
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.create_table('indicators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sector_id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('name_en', sa.String(length=300), nullable=False),
    sa.Column('name_fr', sa.String(length=300), nullable=False),
    sa.Column('name_ar', sa.String(length=300), nullable=False),
    sa.Column('description_en', sa.Text(), nullable=True),
    sa.Column('description_fr', sa.Text(), nullable=True),
    sa.Column('description_ar', sa.Text(), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('frequency', sa.String(length=20), nullable=True),
    sa.Column('source', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sector_id'], ['sectors.id'], name=op.f('fk_indicators_sector_id_sectors'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_indicators'))
    )
    op.create_index(op.f('ix_indicators_id'), 'indicators', ['id'], unique=False)
    op.create_index(op.f('ix_indicators_slug'), 'indicators', ['slug'], unique=True)
    op.create_table('metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wilaya_id', sa.Integer(), nullable=False),
    sa.Column('sector_id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('name_en', sa.String(length=200), nullable=False),
    sa.Column('name_fr', sa.String(length=200), nullable=False),
    sa.Column('name_ar', sa.String(length=200), nullable=False),
    sa.Column('description_en', sa.String(length=500), nullable=True),
    sa.Column('description_fr', sa.String(length=500), nullable=True),
    sa.Column('description_ar', sa.String(length=500), nullable=True),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('period', sa.String(length=20), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('quarter', sa.String(length=5), nullable=True),
    sa.Column('change_percent', sa.Float(), nullable=True),
    sa.Column('change_value', sa.Float(), nullable=True),
    sa.Column('trend', sa.String(length=20), nullable=True),
    sa.Column('source', sa.String(length=200), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sector_id'], ['sectors.id'], name=op.f('fk_metrics_sector_id_sectors'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['wilaya_id'], ['wilayas.id'], name=op.f('fk_metrics_wilaya_id_wilayas'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_metrics'))
    )
    op.create_index(op.f('ix_metrics_id'), 'metrics', ['id'], unique=False)
    op.create_index(op.f('ix_metrics_period'), 'metrics', ['period'], unique=False)
    op.create_index(op.f('ix_metrics_sector_id'), 'metrics', ['sector_id'], unique=False)
    op.create_index(op.f('ix_metrics_slug'), 'metrics', ['slug'], unique=True)
    op.create_index(op.f('ix_metrics_wilaya_id'), 'metrics', ['wilaya_id'], unique=False)
    op.create_index(op.f('ix_metrics_year'), 'metrics', ['year'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tier', sa.String(length=50), nullable=False),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_price_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('cancel_at_period_end', sa.Boolean(), nullable=True),
    sa.Column('current_period_start', sa.DateTime(), nullable=True),
    sa.Column('current_period_end', sa.DateTime(), nullable=True),
    sa.Column('trial_start', sa.DateTime(), nullable=True),
    sa.Column('trial_end', sa.DateTime(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('billing_interval', sa.String(length=20), nullable=True),
    sa.Column('features', sa.Text(), nullable=True),
    sa.Column('api_rate_limit', sa.Integer(), nullable=True),
    sa.Column('data_export_limit', sa.Integer(), nullable=True),
    sa.Column('ai_queries_limit', sa.Integer(), nullable=True),
    sa.Column('stripe_webhook_payload', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_subscriptions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscriptions'))
    )
    op.create_index(op.f('ix_subscriptions_id'), 'subscriptions', ['id'], unique=False)
    op.create_index(op.f('ix_subscriptions_stripe_customer_id'), 'subscriptions', ['stripe_customer_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_stripe_subscription_id'), 'subscriptions', ['stripe_subscription_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=False)
    op.create_table('data_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('indicator_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('period', sa.String(length=20), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=True),
    sa.Column('period_end', sa.DateTime(), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('region_code', sa.String(length=10), nullable=True),
    sa.Column('meta_data', sa.Text(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['indicator_id'], ['indicators.id'], name=op.f('fk_data_points_indicator_id_indicators'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_data_points'))
    )
    op.create_index(op.f('ix_data_points_id'), 'data_points', ['id'], unique=False)
    op.create_table('document_embeddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('embedding', sa.LargeBinary(), nullable=False),
    sa.Column('meta_data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_document_embeddings_document_id_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_embeddings'))
    )
    op.create_index(op.f('ix_document_embeddings_id'), 'document_embeddings', ['id'], unique=False)
    op.create_table('forecasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('metric_id', sa.Integer(), nullable=False),
    sa.Column('wilaya_id', sa.Integer(), nullable=True),
    sa.Column('forecast_period', sa.String(length=20), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('quarter', sa.String(length=5), nullable=True),
    sa.Column('month', sa.Integer(), nullable=True),
    sa.Column('forecast_value', sa.Float(), nullable=False),
    sa.Column('lower_bound', sa.Float(), nullable=True),
    sa.Column('upper_bound', sa.Float(), nullable=True),
    sa.Column('confidence_interval', sa.Float(), nullable=True),
    sa.Column('forecast_horizon', sa.Integer(), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('model_params', sa.Text(), nullable=True),
    sa.Column('mae', sa.Float(), nullable=True),
    sa.Column('mape', sa.Float(), nullable=True),
    sa.Column('rmse', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['metric_id'], ['metrics.id'], name=op.f('fk_forecasts_metric_id_metrics'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['wilaya_id'], ['wilayas.id'], name=op.f('fk_forecasts_wilaya_id_wilayas'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_forecasts'))
    )
    op.create_index(op.f('ix_forecasts_forecast_period'), 'forecasts', ['forecast_period'], unique=False)
    op.create_index(op.f('ix_forecasts_id'), 'forecasts', ['id'], unique=False)
    op.create_index(op.f('ix_forecasts_metric_id'), 'forecasts', ['metric_id'], unique=False)
    op.create_index(op.f('ix_forecasts_wilaya_id'), 'forecasts', ['wilaya_id'], unique=False)
    op.create_index(op.f('ix_forecasts_year'), 'forecasts', ['year'], unique=False)
    op.create_table('subscription_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('previous_tier', sa.String(length=50), nullable=True),
    sa.Column('new_tier', sa.String(length=50), nullable=True),
    sa.Column('previous_status', sa.String(length=50), nullable=True),
    sa.Column('new_status', sa.String(length=50), nullable=True),
    sa.Column('stripe_event_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_event_type', sa.String(length=100), nullable=True),
    sa.Column('event_timestamp', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], name=op.f('fk_subscription_history_subscription_id_subscriptions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscription_history'))
    )
    op.create_index(op.f('ix_subscription_history_id'), 'subscription_history', ['id'], unique=False)
    op.create_index(op.f('ix_subscription_history_stripe_event_id'), 'subscription_history', ['stripe_event_id'], unique=True)
    op.create_table('time_series_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wilaya_id', sa.Integer(), nullable=True),
    sa.Column('sector_id', sa.Integer(), nullable=False),
    sa.Column('indicator_id', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=20), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=True),
    sa.Column('period_end', sa.DateTime(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('quarter', sa.String(length=5), nullable=True),
    sa.Column('month', sa.Integer(), nullable=True),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('source', sa.String(length=200), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('meta_data', sa.Text(), nullable=True),
    sa.Column('is_anomaly', sa.Boolean(), nullable=True),
    sa.Column('is_missing', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['indicator_id'], ['indicators.id'], name=op.f('fk_time_series_data_indicator_id_indicators'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sector_id'], ['sectors.id'], name=op.f('fk_time_series_data_sector_id_sectors'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['wilaya_id'], ['wilayas.id'], name=op.f('fk_time_series_data_wilaya_id_wilayas'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_time_series_data'))
    )
    op.create_index(op.f('ix_time_series_data_id'), 'time_series_data', ['id'], unique=False)
    op.create_index(op.f('ix_time_series_data_indicator_id'), 'time_series_data', ['indicator_id'], unique=False)
    op.create_index(op.f('ix_time_series_data_period'), 'time_series_data', ['period'], unique=False)
    op.create_index(op.f('ix_time_series_data_sector_id'), 'time_series_data', ['sector_id'], unique=False)
    op.create_index(op.f('ix_time_series_data_wilaya_id'), 'time_series_data', ['wilaya_id'], unique=False)
    op.create_index(op.f('ix_time_series_data_year'), 'time_series_data', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_time_series_data_year'), table_name='time_series_data')
    op.drop_index(op.f('ix_time_series_data_wilaya_id'), table_name='time_series_data')
    op.drop_index(op.f('ix_time_series_data_sector_id'), table_name='time_series_data')
    op.drop_index(op.f('ix_time_series_data_period'), table_name='time_series_data')
    op.drop_index(op.f('ix_time_series_data_indicator_id'), table_name='time_series_data')
    op.drop_index(op.f('ix_time_series_data_id'), table_name='time_series_data')
    op.drop_table('time_series_data')
    op.drop_index(op.f('ix_subscription_history_stripe_event_id'), table_name='subscription_history')
    op.drop_index(op.f('ix_subscription_history_id'), table_name='subscription_history')
    op.drop_table('subscription_history')
    op.drop_index(op.f('ix_forecasts_year'), table_name='forecasts')
    op.drop_index(op.f('ix_forecasts_wilaya_id'), table_name='forecasts')
    op.drop_index(op.f('ix_forecasts_metric_id'), table_name='forecasts')
    op.drop_index(op.f('ix_forecasts_id'), table_name='forecasts')
    op.drop_index(op.f('ix_forecasts_forecast_period'), table_name='forecasts')
    op.drop_table('forecasts')
    op.drop_index(op.f('ix_document_embeddings_id'), table_name='document_embeddings')
    op.drop_table('document_embeddings')
    op.drop_index(op.f('ix_data_points_id'), table_name='data_points')
    op.drop_table('data_points')
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_stripe_subscription_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_stripe_customer_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_metrics_year'), table_name='metrics')
    op.drop_index(op.f('ix_metrics_wilaya_id'), table_name='metrics')
    op.drop_index(op.f('ix_metrics_slug'), table_name='metrics')
    op.drop_index(op.f('ix_metrics_sector_id'), table_name='metrics')
    op.drop_index(op.f('ix_metrics_period'), table_name='metrics')
    op.drop_index(op.f('ix_metrics_id'), table_name='metrics')
    op.drop_table('metrics')
    op.drop_index(op.f('ix_indicators_slug'), table_name='indicators')
    op.drop_index(op.f('ix_indicators_id'), table_name='indicators')
    op.drop_table('indicators')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_wilayas_id'), table_name='wilayas')
    op.drop_index(op.f('ix_wilayas_code'), table_name='wilayas')
    op.drop_table('wilayas')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_sectors_slug'), table_name='sectors')
    op.drop_index(op.f('ix_sectors_id'), table_name='sectors')
    op.drop_table('sectors')
    # ### end Alembic commands ###
