"""remove unique constraint from system prompt name

Revision ID: 579f9d74b127
Revises: b5fa0ab11c67
Create Date: 2026-02-20 21:41:50.076031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '579f9d74b127'
down_revision: Union[str, None] = 'b5fa0ab11c67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_system_prompts_name', table_name='system_prompts')
    op.create_index(op.f('ix_system_prompts_name'), 'system_prompts', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_system_prompts_name'), table_name='system_prompts')
    op.create_index('ix_system_prompts_name', 'system_prompts', ['name'], unique=True)
    # ### end Alembic commands ###
