# ============================================
# Boussole - Schemas Package
# ============================================

from app.schemas.user import (
    UserBase,
    UserCreate,
    UserUpdate,
    UserUpdatePassword,
    User,
    UserInDB,
    UserLogin,
    Token,
    TokenPayload,
)
from app.schemas.sector import SectorBase, SectorCreate, SectorUpdate, Sector
from app.schemas.indicator import IndicatorBase, IndicatorCreate, IndicatorUpdate, Indicator
from app.schemas.data_point import (
    DataPointBase,
    DataPointCreate,
    DataPointUpdate,
    DataPoint,
    DataPointBulkCreate,
    DataPointQuery,
)
from app.schemas.wilaya import (
    WilayaBase,
    WilayaCreate,
    WilayaUpdate,
    Wilaya,
    WilayaList,
)
from app.schemas.metric import (
    MetricBase,
    MetricCreate,
    MetricUpdate,
    Metric,
    MetricWithWilaya,
    MetricWithForecast,
    DashboardKPI,
    WilayaHeatmapData,
)
from app.schemas.time_series_data import (
    TimeSeriesDataBase,
    TimeSeriesDataCreate,
    TimeSeriesDataUpdate,
    TimeSeriesData,
    TimeSeriesDataWithDetails,
    TimeSeriesBulkCreate,
    TimeSeriesQuery,
)
from app.schemas.forecast import (
    ForecastBase,
    ForecastCreate,
    Forecast,
    ForecastWithMetric,
    ForecastGenerateRequest,
    ForecastGenerateResponse,
    ForecastTrend,
)
from app.schemas.subscription import (
    SubscriptionBase,
    SubscriptionCreate,
    SubscriptionUpdate,
    Subscription,
    SubscriptionWithUser,
    SubscriptionHistoryBase,
    SubscriptionHistory,
    SubscriptionUsage,
    SubscriptionTier,
    StripeWebhookEvent,
    CheckoutSessionCreate,
    CheckoutSessionResponse,
)
from app.schemas.onboarding import (
    OnboardingPreferencesBase,
    OnboardingPreferencesCreate,
    OnboardingPreferencesUpdate,
    OnboardingPreferences,
    OnboardingStep,
    OnboardingSurvey,
    OnboardingCompleteRequest,
    OnboardingCompleteResponse,
    AvailableWilaya,
    AvailableSector,
    OnboardingData,
)

__all__ = [
    "UserBase",
    "UserCreate",
    "UserUpdate",
    "UserUpdatePassword",
    "User",
    "UserInDB",
    "UserLogin",
    "Token",
    "TokenPayload",
    "SectorBase",
    "SectorCreate",
    "SectorUpdate",
    "Sector",
    "IndicatorBase",
    "IndicatorCreate",
    "IndicatorUpdate",
    "Indicator",
    "DataPointBase",
    "DataPointCreate",
    "DataPointUpdate",
    "DataPoint",
    "DataPointBulkCreate",
    "DataPointQuery",
    "WilayaBase",
    "WilayaCreate",
    "WilayaUpdate",
    "Wilaya",
    "WilayaList",
    "MetricBase",
    "MetricCreate",
    "MetricUpdate",
    "Metric",
    "MetricWithWilaya",
    "MetricWithForecast",
    "DashboardKPI",
    "WilayaHeatmapData",
    "TimeSeriesDataBase",
    "TimeSeriesDataCreate",
    "TimeSeriesDataUpdate",
    "TimeSeriesData",
    "TimeSeriesDataWithDetails",
    "TimeSeriesBulkCreate",
    "TimeSeriesQuery",
    "ForecastBase",
    "ForecastCreate",
    "Forecast",
    "ForecastWithMetric",
    "ForecastGenerateRequest",
    "ForecastGenerateResponse",
    "ForecastTrend",
    "SubscriptionBase",
    "SubscriptionCreate",
    "SubscriptionUpdate",
    "Subscription",
    "SubscriptionWithUser",
    "SubscriptionHistoryBase",
    "SubscriptionHistory",
    "SubscriptionUsage",
    "SubscriptionTier",
    "StripeWebhookEvent",
    "CheckoutSessionCreate",
    "CheckoutSessionResponse",
]
